### ISSUE TITLE
Error importing wx after upgrading to wxmac-3.0.1 (Python 2.7.5, OS X)

### ISSUE THREAD

**Issue by spmaniato** [VerifiableRobotics/LTLMoP#75]
Maybe the error indicates a problem with just my installation?

Cameron, could you take a quick look please?

<pre>
python specEditor.py 
Traceback (most recent call last):
  File "specEditor.py", line 13, in <module>
    import wx, wx.richtext, wx.stc
  File "/Library/Python/2.7/site-packages/wx-2.9.4-osx_cocoa/wx/__init__.py", line 45, in <module>
    from wx._core import *
  File "/Library/Python/2.7/site-packages/wx-2.9.4-osx_cocoa/wx/_core.py", line 4, in <module>
    import _core_
ImportError: dlopen(/Library/Python/2.7/site-packages/wx-2.9.4-osx_cocoa/wx/_core_.so, 2): Library not loaded: /opt/local/lib/libwx_osx_cocoau_xrc-2.9.4.0.0.dylib
  Referenced from: /Library/Python/2.7/site-packages/wx-2.9.4-osx_cocoa/wx/_core_.so
  Reason: image not found
</pre>

<pre>
Python 2.7.5 (default, Mar  9 2014, 22:15:05) 
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import wx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/wx-2.9.4-osx_cocoa/wx/__init__.py", line 45, in <module>
    from wx._core import *
  File "/Library/Python/2.7/site-packages/wx-2.9.4-osx_cocoa/wx/_core.py", line 4, in <module>
    import _core_
ImportError: dlopen(/Library/Python/2.7/site-packages/wx-2.9.4-osx_cocoa/wx/_core_.so, 2): Library not loaded: /opt/local/lib/libwx_osx_cocoau_xrc-2.9.4.0.0.dylib
  Referenced from: /Library/Python/2.7/site-packages/wx-2.9.4-osx_cocoa/wx/_core_.so
  Reason: image not found
</pre>

**Comment by spmaniato** [comment]
Question and answer: http://stackoverflow.com/questions/26306218/wxmac-image-not-found-python-2-7-5-os-x
